export interface SutraVerse {
  korean: string
  chinese?: string
}

export interface Sutra {
  id: string
  title: string
  description: string
  verses: SutraVerse[]
}

export const SUTRAS: Sutra[] = [
  {
    id: 'heart-sutra',
    title: '반야심경',
    description: '반야바라밀다심경 - 260자로 불교의 핵심을 담은 경전',
    verses: [
      { korean: '관자재보살이 깊은 반야바라밀다를 행할 때', chinese: '觀自在菩薩 行深般若波羅蜜多時' },
      { korean: '오온이 공한 것을 비추어 보고', chinese: '照見五蘊皆空' },
      { korean: '일체의 고액을 건넜느니라.', chinese: '度一切苦厄' },
      { korean: '사리자여, 색이 공과 다르지 않고', chinese: '舍利子 色不異空' },
      { korean: '공이 색과 다르지 않으며', chinese: '空不異色' },
      { korean: '색이 곧 공이요 공이 곧 색이니', chinese: '色卽是空 空卽是色' },
      { korean: '수상행식도 이와 같으니라.', chinese: '受想行識 亦復如是' },
      { korean: '사리자여, 이 모든 법은 공하여', chinese: '舍利子 是諸法空相' },
      { korean: '나지도 멸하지도 않으며', chinese: '不生不滅' },
      { korean: '더럽지도 깨끗하지도 않으며', chinese: '不垢不淨' },
      { korean: '늘지도 줄지도 않느니라.', chinese: '不增不減' },
      { korean: '그러므로 공 가운데는 색이 없고', chinese: '是故空中無色' },
      { korean: '수상행식도 없으며', chinese: '無受想行識' },
      { korean: '눈, 귀, 코, 혀, 몸, 뜻도 없고', chinese: '無眼耳鼻舌身意' },
      { korean: '색, 소리, 냄새, 맛, 감촉, 법도 없으며', chinese: '無色聲香味觸法' },
      { korean: '눈의 세계도 없고 의식의 세계까지도 없으며', chinese: '無眼界 乃至無意識界' },
      { korean: '무명도 없고 무명이 다함까지도 없으며', chinese: '無無明 亦無無明盡' },
      { korean: '늙고 죽음도 없고 늙고 죽음이 다함까지도 없으며', chinese: '乃至無老死 亦無老死盡' },
      { korean: '고, 집, 멸, 도도 없고', chinese: '無苦集滅道' },
      { korean: '지혜도 없고 얻음도 없느니라.', chinese: '無智亦無得' },
      { korean: '얻을 것이 없는 까닭에', chinese: '以無所得故' },
      { korean: '보살은 반야바라밀다에 의지하므로', chinese: '菩提薩埵 依般若波羅蜜多故' },
      { korean: '마음에 걸림이 없고', chinese: '心無罣礙' },
      { korean: '걸림이 없으므로 두려움이 없어', chinese: '無罣礙故 無有恐怖' },
      { korean: '뒤바뀐 꿈같은 생각을 멀리 여의어', chinese: '遠離顚倒夢想' },
      { korean: '마침내 열반에 이르느니라.', chinese: '究竟涅槃' },
      { korean: '삼세의 모든 부처님도 반야바라밀다에 의지하므로', chinese: '三世諸佛 依般若波羅蜜多故' },
      { korean: '아뇩다라삼먁삼보리를 얻었느니라.', chinese: '得阿耨多羅三藐三菩提' },
      { korean: '그러므로 알라. 반야바라밀다는', chinese: '故知般若波羅蜜多' },
      { korean: '가장 신비로운 주문이며', chinese: '是大神呪' },
      { korean: '가장 밝은 주문이며', chinese: '是大明呪' },
      { korean: '가장 높은 주문이며', chinese: '是無上呪' },
      { korean: '무엇과도 견줄 수 없는 주문이니', chinese: '是無等等呪' },
      { korean: '능히 일체의 고통을 없애고', chinese: '能除一切苦' },
      { korean: '진실하여 허망하지 않느니라.', chinese: '眞實不虛' },
      { korean: '이제 반야바라밀다의 주문을 말하리라.', chinese: '故說般若波羅蜜多呪' },
      { korean: '아제아제 바라아제 바라승아제 모지사바하', chinese: '揭諦揭諦 波羅揭諦 波羅僧揭諦 菩提薩婆訶' },
    ],
  },
  {
    id: 'cheonsu',
    title: '천수경 (신묘장구대다라니)',
    description: '천수천안관세음보살의 대비주',
    verses: [
      { korean: '나모라 다나다라 야야' },
      { korean: '나막 알야 바로기제 새바라야' },
      { korean: '모지 사다바야 마하사다바야' },
      { korean: '마하 가로니가야' },
      { korean: '옴 살바 바예수 다라나 가라야' },
      { korean: '다사명 나막까리다바' },
      { korean: '이맘 알야 바로기제 새바라 다바' },
      { korean: '나막 조라 나막조라 지리니' },
      { korean: '시바라야 사바하' },
    ],
  },
  {
    id: 'diamond-sutra-key',
    title: '금강경 (핵심 구절)',
    description: '금강반야바라밀경 - 핵심 사구게 모음',
    verses: [
      { korean: '무릇 형상이 있는 것은 모두 허망하니', chinese: '凡所有相 皆是虛妄' },
      { korean: '만약 모든 형상이 형상 아닌 줄 보면', chinese: '若見諸相非相' },
      { korean: '곧 여래를 보리라.', chinese: '卽見如來' },
      { korean: '', chinese: '' },
      { korean: '마땅히 머무는 바 없이 그 마음을 내라.', chinese: '應無所住而生其心' },
      { korean: '', chinese: '' },
      { korean: '과거 마음도 얻을 수 없고', chinese: '過去心不可得' },
      { korean: '현재 마음도 얻을 수 없고', chinese: '現在心不可得' },
      { korean: '미래 마음도 얻을 수 없느니라.', chinese: '未來心不可得' },
      { korean: '', chinese: '' },
      { korean: '일체의 유위법은', chinese: '一切有爲法' },
      { korean: '꿈과 같고 환상과 같고', chinese: '如夢幻泡影' },
      { korean: '이슬과 같고 번개와 같으니', chinese: '如露亦如電' },
      { korean: '마땅히 이와 같이 관하라.', chinese: '應作如是觀' },
    ],
  },
  {
    id: 'namu-amitabul',
    title: '나무아미타불',
    description: '아미타불의 명호를 부르는 염불 수행',
    verses: [
      { korean: '나무아미타불 (南無阿彌陀佛)' },
      { korean: '' },
      { korean: '한없는 빛의 부처님께 귀의합니다.' },
      { korean: '한없는 수명의 부처님께 귀의합니다.' },
      { korean: '' },
      { korean: '아미타불의 48대원에 의지하여' },
      { korean: '일체 중생이 극락정토에 왕생하기를 발원합니다.' },
      { korean: '' },
      { korean: '원컨대 이 공덕으로' },
      { korean: '일체에 두루하여' },
      { korean: '우리와 중생이' },
      { korean: '다 함께 불도를 이루어지이다.' },
    ],
  },
  {
    id: 'om-mani',
    title: '옴마니반메훔',
    description: '관세음보살의 육자대명진언',
    verses: [
      { korean: '옴 마니 반메 훔 (唵嘛呢叭咪吽)' },
      { korean: '' },
      { korean: '옴 — 신구의 삼업을 청정케 하고' },
      { korean: '마 — 인욕을 성취하게 하며' },
      { korean: '니 — 지계를 성취하게 하고' },
      { korean: '반 — 정진을 성취하게 하며' },
      { korean: '메 — 선정을 성취하게 하고' },
      { korean: '훔 — 지혜를 성취하게 하나니' },
      { korean: '' },
      { korean: '이 여섯 글자에 육바라밀의 뜻이 모두 담겨 있느니라.' },
    ],
  },
  {
    id: 'beopseong-ge',
    title: '법성게',
    description: '의상 대사의 화엄일승법계도 - 화엄 사상 핵심 30구',
    verses: [
      { korean: '법성은 원융하여 두 모습이 없고', chinese: '法性圓融無二相' },
      { korean: '모든 법은 부동하여 본래 고요하다.', chinese: '諸法不動本來寂' },
      { korean: '이름도 없고 모습도 없어 일체가 끊겼으니', chinese: '無名無相絶一切' },
      { korean: '깨달은 지혜로 알 뿐 다른 경계가 아니다.', chinese: '證智所知非餘境' },
      { korean: '', chinese: '' },
      { korean: '참된 성품은 깊고도 지극히 미묘하여', chinese: '眞性甚深極微妙' },
      { korean: '자성을 지키지 않고 인연 따라 이루어진다.', chinese: '不守自性隨緣成' },
      { korean: '하나 가운데 일체요, 일체 가운데 하나라', chinese: '一中一切多中一' },
      { korean: '하나가 곧 일체요, 일체가 곧 하나이다.', chinese: '一卽一切多卽一' },
      { korean: '', chinese: '' },
      { korean: '한 티끌 가운데 시방세계를 머금고', chinese: '一微塵中含十方' },
      { korean: '모든 티끌 가운데 또한 그러하다.', chinese: '一切塵中亦如是' },
      { korean: '한없는 시간이 곧 한 생각이요', chinese: '無量遠劫卽一念' },
      { korean: '한 생각이 곧 한없는 시간이다.', chinese: '一念卽是無量劫' },
      { korean: '', chinese: '' },
      { korean: '본래 자리에 그대로 앉아', chinese: '舊來不動名爲佛' },
      { korean: '움직임 없으니 이름하여 부처라 한다.', chinese: '' },
    ],
  },
  {
    id: 'sahong-seowon',
    title: '사홍서원',
    description: '보살이 세우는 네 가지 큰 서원',
    verses: [
      { korean: '중생을 다 건지오리다.', chinese: '衆生無邊誓願度' },
      { korean: '번뇌를 다 끊으오리다.', chinese: '煩惱無盡誓願斷' },
      { korean: '법문을 다 배우오리다.', chinese: '法門無量誓願學' },
      { korean: '불도를 다 이루오리다.', chinese: '佛道無上誓願成' },
      { korean: '', chinese: '' },
      { korean: '자성중생서원도', chinese: '自性衆生誓願度' },
      { korean: '자성번뇌서원단', chinese: '自性煩惱誓願斷' },
      { korean: '자성법문서원학', chinese: '自性法門誓願學' },
      { korean: '자성불도서원성', chinese: '自性佛道誓願成' },
      { korean: '', chinese: '' },
      { korean: '내 안의 중생을 건지고, 내 안의 번뇌를 끊으며,' },
      { korean: '내 안의 법문을 배우고, 내 안의 불도를 이루리라.' },
    ],
  },
  {
    id: 'chamhoe-ge',
    title: '참회게',
    description: '예전부터 지은 모든 악업을 참회하는 게송',
    verses: [
      { korean: '아석소조제악업', chinese: '我昔所造諸惡業' },
      { korean: '개유무시탐진치', chinese: '皆由無始貪瞋癡' },
      { korean: '종신구의지소생', chinese: '從身口意之所生' },
      { korean: '일체아금개참회', chinese: '一切我今皆懺悔' },
      { korean: '', chinese: '' },
      { korean: '내가 지난날 지은 모든 악업은' },
      { korean: '비롯할 수 없는 옛적부터' },
      { korean: '탐냄과 성냄과 어리석음으로 말미암아' },
      { korean: '몸과 입과 뜻으로 지었으니' },
      { korean: '제가 이제 모두 참회합니다.' },
      { korean: '', chinese: '' },
      { korean: '참회진언', chinese: '懺悔眞言' },
      { korean: '옴 살바 못자모지 사다야 사바하' },
    ],
  },
  {
    id: 'muvsang-ge',
    title: '무상게',
    description: '제행무상 - 모든 것은 흘러간다',
    verses: [
      { korean: '제행무상', chinese: '諸行無常' },
      { korean: '시생멸법', chinese: '是生滅法' },
      { korean: '생멸멸이', chinese: '生滅滅已' },
      { korean: '적멸위락', chinese: '寂滅爲樂' },
      { korean: '', chinese: '' },
      { korean: '모든 것은 무상하니' },
      { korean: '이는 생하고 멸하는 법이라.' },
      { korean: '생과 멸이 다 멸하면' },
      { korean: '고요한 적멸이 즐거움이니라.' },
      { korean: '', chinese: '' },
      { korean: '꽃이 피면 지고, 달이 차면 기울며,' },
      { korean: '오는 것은 가고 만남은 헤어짐이 있으니' },
      { korean: '집착할 것이 없음을 보라.' },
    ],
  },
  {
    id: 'hoehyang-ge',
    title: '회향게',
    description: '수행 공덕을 일체 중생에게 돌려주는 게송',
    verses: [
      { korean: '원이차공덕', chinese: '願以此功德' },
      { korean: '보급어일체', chinese: '普及於一切' },
      { korean: '아등여중생', chinese: '我等與衆生' },
      { korean: '당생극락국', chinese: '當生極樂國' },
      { korean: '', chinese: '' },
      { korean: '동견무량수', chinese: '同見無量壽' },
      { korean: '개공성불도', chinese: '皆共成佛道' },
      { korean: '', chinese: '' },
      { korean: '원하옵나니 이 공덕으로' },
      { korean: '일체에 두루하여' },
      { korean: '저희와 모든 중생이' },
      { korean: '함께 극락국에 태어나' },
      { korean: '한가지로 무량수불을 뵙고' },
      { korean: '다 함께 불도를 이루어지이다.' },
    ],
  },
  {
    id: 'ilche-yusimjo',
    title: '일체유심조',
    description: '화엄경 - 모든 것은 마음이 짓는다',
    verses: [
      { korean: '약인욕요지', chinese: '若人欲了知' },
      { korean: '삼세일체불', chinese: '三世一切佛' },
      { korean: '응관법계성', chinese: '應觀法界性' },
      { korean: '일체유심조', chinese: '一切唯心造' },
      { korean: '', chinese: '' },
      { korean: '만약 누군가 알고자 한다면' },
      { korean: '삼세 모든 부처님을' },
      { korean: '마땅히 법계의 성품을 관하라.' },
      { korean: '모든 것은 오직 마음이 짓느니라.', chinese: '一切唯心造' },
      { korean: '', chinese: '' },
      { korean: '심여공화사', chinese: '心如工畫師' },
      { korean: '능화제세간', chinese: '能畵諸世間' },
      { korean: '', chinese: '' },
      { korean: '마음은 공교한 화가와 같아' },
      { korean: '능히 모든 세간을 그려낸다.' },
    ],
  },
  {
    id: 'sinsim-myeong',
    title: '신심명 (핵심)',
    description: '승찬 대사의 신심명 - 도에 이르는 마음의 길',
    verses: [
      { korean: '지도무난', chinese: '至道無難' },
      { korean: '유혐간택', chinese: '唯嫌揀擇' },
      { korean: '단막증애', chinese: '但莫憎愛' },
      { korean: '통연명백', chinese: '洞然明白' },
      { korean: '', chinese: '' },
      { korean: '지극한 도는 어렵지 않으니' },
      { korean: '오직 가려서 택함을 꺼릴 뿐이다.' },
      { korean: '미워하고 사랑함만 없으면' },
      { korean: '확연히 명백하리라.' },
      { korean: '', chinese: '' },
      { korean: '호리유차', chinese: '毫釐有差' },
      { korean: '천지현격', chinese: '天地懸隔' },
      { korean: '', chinese: '' },
      { korean: '털끝만큼이라도 차이가 있으면' },
      { korean: '하늘과 땅처럼 벌어진다.' },
      { korean: '', chinese: '' },
      { korean: '일심불생', chinese: '一心不生' },
      { korean: '만법무구', chinese: '萬法無咎' },
      { korean: '', chinese: '' },
      { korean: '한 마음이 생기지 않으면' },
      { korean: '만 가지 법에 허물이 없다.' },
    ],
  },
  {
    id: 'sangsan-eo',
    title: '산은 산이요',
    description: '성철 스님 법어 - 청원유신 선사 게송',
    verses: [
      { korean: '산시산 수시수', chinese: '山是山 水是水' },
      { korean: '산은 산이요 물은 물이로다.' },
      { korean: '', chinese: '' },
      { korean: '노승이 삼십 년 전 참선하기 전에는' },
      { korean: '산을 보면 산이요, 물을 보면 물이었다.' },
      { korean: '', chinese: '' },
      { korean: '그 후 선지식을 만나' },
      { korean: '한 깨달음의 자리에 들어서서는' },
      { korean: '산을 보아도 산이 아니요, 물을 보아도 물이 아니더라.' },
      { korean: '', chinese: '' },
      { korean: '이제 마침내 쉬는 자리에 이르러' },
      { korean: '예전과 같이' },
      { korean: '산을 보니 다만 산일 뿐이요' },
      { korean: '물을 보니 다만 물일 뿐이로다.' },
    ],
  },
]

// 만트라 목록 (염주용)
export const MANTRAS = [
  { id: 'namu-amitabul', label: '나무아미타불', text: '나무아미타불' },
  { id: 'om-mani', label: '옴마니반메훔', text: '옴 마니 반메 훔' },
  { id: 'namu-gwaneum', label: '나무관세음보살', text: '나무관세음보살' },
  { id: 'namu-jijang', label: '나무지장보살', text: '나무지장보살' },
]
